### ISSUE TITLE
Add the Aurora design system (Government of Canada)

### ISSUE THREAD

**Issue by s-duffey** [alexpate/awesome-design-systems#128]
Built by the Digital Collaboration Division in the Government of Canada, Aurora is a new design system that is currently in alpha. 

Aurora is open source, multi-disciplinary and free for anyone to use. 

See the design system here: https://gctools-outilsgc.github.io/design-system-code/

**Comment by s-duffey** [comment]
New URL is [design.gccollab.ca ](https://design.gccollab.ca/)

**Comment by alexpate** [comment]
Thanks for the suggestion. Added in https://github.com/alexpate/awesome-design-systems/commit/17ec441794c0ef6aea8fe6d92e0fe3a406c44cbc
