### ISSUE TITLE
make it a table?

### ISSUE THREAD

**Issue by mhsenkow** [alexpate/awesome-design-systems#17]
I like your use of icons to show whats in each but because each line is differing in length it becomes really hard to read and the icons become next to useless (you have to look down and up to see whats what). I think you'd be better off with a table display.

**Comment by alexpate** [comment]
Thanks for the suggestion. I agree, the icons are pretty hard to scan. Do you think the icons should be in one column, or each icon have it's own column?

**Comment by alexpate** [comment]
Just implemented this, sooo much easier to read. Cheers man!

**Comment by mhsenkow** [comment]
oh wow I don't think I've ever had an issue implemented on github before. very cool, definitely more scannable!
