### ISSUE TITLE
Add column for license of each design systems.

### ISSUE THREAD

**Issue by slemeur** [alexpate/awesome-design-systems#38]
It would be interesting to provide the licenses for each of the design systems from the collection. 
This way any reader would have an idea of how the design systems can be used, embed, altered and extended. 
Also, certain of the design systems are open source and welcoming contributions ;)

**Comment by alexpate** [comment]
Interesting suggestion. I'm not sure if it would add much value though. I think it's better to keep the license for each project/repo in it's repo.
