### ISSUE TITLE
Possible other libraries

### ISSUE THREAD

**Issue by spentacular** [alexpate/awesome-design-systems#42]
Hey! I've been keeping a list of these for a while as I've come across. Some may not fit into your plan so I figure it would be easier to post here instead of spamming PR's.

- [Spectre.css](https://picturepan2.github.io/spectre/)
- [mini.css](http://minicss.org/)
- [Stack Exchange Stacks UI](http://stackexchange.github.io/stacks-ui/) - *No public repo for this one*
- [Bulma](http://bulma.io/)
- [Blaze CSS](http://blazecss.com/)
- [Help Scout](http://style.helpscout.com/) - *Covers several categories*
- [Heroku Purple3](https://purple3.herokuapp.com/)
- [Element](http://element.eleme.io/)
- [UIKit](https://getuikit.com/)

**Comment by spentacular** [comment]
As per #41 I think the Stacks UI and Help Scout ones fit into the company specific. Heroku's is super nice but based on Tachyons

**Comment by alexpate** [comment]
Thanks for collating these! Yeah most of them look relevant I would say

**Comment by spentacular** [comment]
Thanks! I saw you added them so I'm going to close this one.
