### ISSUE TITLE
Change link for Material Design 

### ISSUE THREAD

**Issue by mariahmuscato** [alexpate/awesome-design-systems#52]
Love this list of design systems. I hope to get HubSpot's system up here one day (ours is still private). 

Just wanted to add a suggestion...

In my experience it's been challenging to navigate from material.io to the actual style guide. [This link](https://material.io/guidelines/#introduction-goals) is a shortcut I've found extremely useful.

**Comment by alexpate** [comment]
Ahh thanks, great suggestion. Will push an update.

And yes, totally add it if you ever open source it!
