### ISSUE TITLE
Trello and Rambler

### ISSUE THREAD

**Issue by jordanslon** [alexpate/awesome-design-systems#68]
https://design.trello.com/components/activity
https://rambler-digital-solutions.github.io/rambler-ui/#/components?_k=al8xxh

**Comment by mhrabiee** [comment]
https://design.trello.com/components/activity is already in the list with name of Trello - Nachos
Rambler looks fine.

**Comment by alexpate** [comment]
I think we should still add it. The design/development principles are still the same regardless of the language.

**Comment by mhrabiee** [comment]
So i will submit a PR
