### ISSUE TITLE
HubSpot Canvas Design System

### ISSUE THREAD

**Issue by mariahmuscato** [alexpate/awesome-design-systems#93]
I'd love to add the HubSpot Canvas Design System to this list. 

Here is a link to our public facing UI Library: [https://canvas.hubspot.com/](https://canvas.hubspot.com/)

We're also writing a blog series on the why we created HubSpot Canvas. Not sure if there's a place to include links but figured I'd add those articles here.

**Post 1**
[How building a design system empowers your team to focus on people — not pixels.](https://medium.com/hubspot-product/people-over-pixels-b962c359a14d)

**Post 2**
[How to gain widespread adoption of your design system.](https://medium.com/@julienerg/how-to-gain-widespread-adoption-of-your-design-system-29d1b142b158)

**Comment by alexpate** [comment]
This looks awesome, have just added it.

Thanks for suggesting!
